config/routes.rb
SimpleFeedback::Application.routes.draw do
  root to: 'feedbacks#index'

  namespace :admin do
    resources :feedbacks, only: :index
  end

  resources :feedbacks
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :rating, :author, :body

  validates :body, presence: {message: "must contain some kind feedback" }
end

app/models/rage_communicator.rb
class RageCommunicator
  def initialize(unraging_thing)
    @unraging_thing = unraging_thing
  end

  def name
    name = @unraging_thing.author.empty? ? "Anonymous" : @unraging_thing.author
    "RageHuman say: " + name
  end

  def body
    "GRRRRRRRR!!!" + @unraging_thing.body.upcase
  end

  def rating
    @unraging_thing.rating
  end
end

app/models/raw_text_converter.rb
class RawTextConverter
	
	def initialize(rawtext)
		@rawtext = rawtext
	end

	def enlarge(text)

	end

end

app/controllers/admin/feedbacks_controller.rb
module Admin
  class FeedbacksController < ApplicationController
    def index
      unless params[:pw] == 'jabu'
        redirect_to root_path
      else
        @feedbacks = Feedback.all
      end
    end
  end
end

app/controllers/admin/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def index
  end

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.create(params[:feedback])
    if @feedback.save
      flash[:success] = "Your feedback has been logged"
    else
      flash[:alert] = @feedback.errors.full_messages
    end
    redirect_to feedbacks_path
  end
end

app/controllers/markdown/markdown_controller.rb
class MarkdownController << ApplicationController

  def new
    @text =
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/feedbacks/index.html.erb
<% @feedbacks.each do |f| %>
  <p><%= f.body %></p>
<% end %>

app/views/feedbacks/index.html.erb
<h1>Add some spot feedback</h1>

<%= render 'shared/flash_success' %>
<%= link_to 'Add some feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>Give me a spot feedback</h1>

<% if !Array(flash[:alert]).empty? %>
  <ul>
  <% Array(flash[:alert]).each do |err| %>
    <li><%= err %></li>
  <% end %>
  </ul>
<% end %>

<div id="preview" style="border: solid 1px red; position: absolute; top: 50%; right: 5px; width: 40%">
  <p></p>
</div>

<%= form_for @feedback do |f| %>
  <%= f.label :author %><br>
  <%= f.text_field :author %><p style="display:inline"><em>(optional)</em></p><br>

  <%= f.label :body %><br>
  <%= f.text_area :body %>

  <%= f.label :rating %><br>
  <%= f.select :rating, *[1..5] %><span><em>5 is the best!</em></span><br>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <title>SimpleFeedback</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_feedback.html.erb
<h1><%= @feedback.author.empty? ? "Anonymous" : @feedback.author %> says...</h1>
<p><%= @feedback.body %></p>
<p>And rates that lecture as...<%= @feedback.rating %></p>

app/views/shared/_flash_success.html.erb
<ul>
  <% if (flash[:success] || flash[:alert]) %>
    <li><%= (flash[:success] || flash[:alert]) %></li>
  <% end %>
</ul>